const fieldRequireFormPPDBAdmin = [
  "from_school",
  "fullname",
  "phone",
  "email",
  "password",
  "nisn",
  "nik",
  "gender",
  "no_certificate_registration",
  "religion",
  "weight",
  "height",
  "gender",
  "foto_nisn",
  "foto_kartu_keluarga",

  "class1",
  "class2",
  "class3",

  "special_needs",
  "date",
  "city",
  "alamat",
  "rt",
  "rw",
  "kelurahan",
  "kecamatan",
  "father_name",
  "father_nik",

  "father_date",
  "father_city",
  "father_education",
  "father_job",
  "father_income",
  "mother_name",
  "mother_nik",
  "mother_date",
  "mother_city",
  "mother_education",

  "mother_job",
  "mother_income",
  "type_registration",
  "no_examinee",
  "no_serial_diploma",
  "no_serial_skhus",
  "extra1",
  "extra2",
  "uniform1",
  "uniform2",

  "uniform3",
  "uniform4",
];

const fieldRequireFormPPDBStudent = [
  "nisn",
  "nik",
  "gender",
  "no_certificate_registration",
  "religion",
  "weight",
  "height",
  "gender",
  "foto_nisn",
  "foto_kartu_keluarga",

  "special_needs",
  "date",
  "city",
  "alamat",
  "rt",
  "rw",
  "kelurahan",
  "kecamatan",
  "father_name",
  "father_nik",

  "father_date",
  "father_city",
  "father_education",
  "father_job",
  "father_income",
  "mother_name",
  "mother_nik",
  "mother_date",
  "mother_city",
  "mother_education",

  "mother_job",
  "mother_income",
  "type_registration",
  "no_examinee",
  "no_serial_diploma",
  "no_serial_skhus",
  "extra1",
  "extra2",
  "uniform1",
  "uniform2",
  "uniform3",
  "uniform4",
];

export { fieldRequireFormPPDBAdmin, fieldRequireFormPPDBStudent };
